name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          repositories_affiliations: owner, organization_member
          repositories_skipped: |
            @use.patterns

            # Skip a specific repository
            -bhsd-harry/codemirror-mediawiki
            -bhsd-harry/types-mediawiki
            -bhsd-harry/mediawiki
            -bhsd-harry/PPE

            # Skip repositories matching a given pattern
            inpageedit/*

            # Include back a previously skipped repository
          commits_authoring: bhsd, bhsd-harry
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_details: percentage
