name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          repositories_affiliations: owner, organization_member
          config_timezone: America/Los_Angeles
          repositories_skipped: |
            @use.patterns

            # Skip a specific repository (both patterns are equivalent)
            -bhsd-harry/codemirror-mediawiki
            -bhsd-harry/types-mediawiki
            -bhsd-harry/mediawiki

            # Skip repositories matching a given pattern
            inpageedit/*
            LLWiki/*

            # Include back a previously skipped repository
            +LLWiki/MinervaMenus
            +LLWiki/LLWikiMessages
            +LLWiki/ComboBox
            +LLWiki/FrontEnd
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_details: percentage
