name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          plugin_languages: yes
          plugin_languages_skipped: bhsd-harry/codemirror-mediawiki
          plugin_languages_analysis_timeout: 60
