name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: bhsd-harry/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          repositories_skipped: |
            bhsd-harry/codemirror-mediawiki
            bhsd-harry/types-mediawiki
            bhsd-harry/mediawiki
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_indepth_custom: LLWiki/MinervaMenus, LLWiki/ComboBox
          plugin_languages_ignored: Jupyter Notebook
