name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 1 * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          repositories_skipped: |
            bhsd-harry/wikiparser-typescript
            bhsd-harry/types-mediawiki
            bhsd-harry/eslint-plugin-unicorn
            bhsd-harry/eslint-plugin-jsdoc
            bhsd-harry/mediawiki
            bhsd-harry/PPE
            bhsd-harry/eslint-browserify
            bhsd-harry/stylelint-browserify
          plugin_languages: yes
          plugin_languages_details: percentage
