name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          repositories_skipped: |
            bhsd-harry/codemirror-mediawiki
            bhsd-harry/types-mediawiki
            bhsd-harry/mediawiki
            bhsd-harry/PPE
          commits_authoring: bhsd, bhsd-harry
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_indepth_custom: LLWiki/MinervaMenus, LLWiki/ComboBox, LLWiki/FrontEnd
