name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}
          base: ""
          repositories_skipped: |
            bhsd-harry/codemirror-mediawiki
            bhsd-harry/types-mediawiki
            bhsd-harry/mediawiki
          commits_authoring: bhsd, bhsd-harry
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_analysis_timeout: 60
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          plugin_languages_indepth_custom: LLWiki/MinervaMenus, LLWiki/ComboBox
          plugin_languages_ignored: Jupyter Notebook
